[package]
name = "rpi-mqtt-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
libc = "0.2"


[build-dependencies]
bindgen = "0.72.1"
